services:
  - type: web
    name: student-auto-deployer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GITHUB_USERNAME
        sync: false